USE STUDENTDATA;

CREATE DATABASE STUDENTDATA 

CREATE TABLE STUDENT (
NAME VARCHAR(20),
ROLLNO INT NOT NULL PRIMARY KEY,
BRANCH VARCHAR(20),
CITY VARCHAR(20),
CreatedBy VARCHAR(20) DEFAULT 'DINESH',
CreatedDate DATETIME DEFAULT GETDATE(),
ModifiedBy VARCHAR(20) DEFAULT NULL,
ModifiedDate DATETIME DEFAULT NULL,
)

DROP TABLE STUDENT

SELECT * FROM STUDENT

INSERT INTO STUDENT (NAME,ROLLNO,BRANCH,CITY) VALUES
('VIJAYA',150,'CSE','CHENNAI'),
('SITA',202,'ETC','KOLKATA'),
('RAVI',300,'EEE','DELHI'),
('BASU',165,'ETC','CHENNAI'),
('RASMI',107,'ETC','RKL'),
('KARAN',111,'CSE','CTC'),
('REKHA',117,'BME','BBSR');


SELECT BRANCH, COUNT(*) AS NumberOfStudents
FROM STUDENT
GROUP BY BRANCH;

SELECT BRANCH, COUNT(*) AS NumberOfStudents FROM STUDENT WHERE BRANCH LIKE 'E%' GROUP BY BRANCH

ALTER TABLE STUDENT ADD MARKS INT;

ALTER TABLE STUDENT ALTER COLUMN NAME VARCHAR(25);

DELETE STUDENT WHERE BRANCH ='ETC';


--ALTER TABLE STUDENT RENAME TO STUDENTINFORMATION;
Exec sp_rename 'STUDENT', 'StudentInformation'

DELETE FROM STUDENT
DROP TABLE STUDENT;

SELECT * FROM StudentInformation
Exec sp_rename 'StudentInformation','STUDENT'
SELECT * FROM STUDENT

