USE STUDENTDATA;

CREATE DATABASE STUDENTDATA 

CREATE TABLE STUDENT (
NAME VARCHAR(20),
ROLLNO INT NOT NULL PRIMARY KEY,
BRANCH VARCHAR(20),
CITY VARCHAR(20),
CreatedBy VARCHAR(20),
CreatedDate DATETIME,
ModifiedBy VARCHAR(20),
ModifiedDate DATETIME,
)

DROP TABLE STUDENT

SELECT * FROM STUDENT

INSERT INTO STUDENT (NAME,ROLLNO,BRANCH,CITY,CreatedBy,CreatedDate,ModifiedBy,ModifiedDate) VALUES
('VIJAYA',150,'CSE','CHENNAI','DINESH',GETDATE(),NULL,NULL),
('SITA',202,'ETC','KOLKATA','DINESH',GETDATE(),NULL,NULL),
('RAVI',300,'EEE','DELHI','DINESH',GETDATE(),NULL,NULL),
('BASU',165,'ETC','CHENNAI','DINESH',GETDATE(),NULL,NULL),
('RASMI',107,'ETC','RKL','DINESH',GETDATE(),NULL,NULL),
('KARAN',111,'CSE','CTC','DINESH',GETDATE(),NULL,NULL),
('REKHA',117,'BME','BBSR','DINESH',GETDATE(),NULL,NULL);

SELECT COUNT(NAME),BRANCH,NAME FROM STUDENT GROUP BY BRANCH;

SELECT BRANCH, COUNT(*) AS NumberOfStudents
FROM STUDENT
GROUP BY BRANCH;

SELECT BRANCH, COUNT(*) AS NumberOfStudents FROM STUDENT WHERE BRANCH LIKE 'E%' GROUP BY BRANCH

ALTER TABLE STUDENT ADD MARKS INT;

ALTER TABLE STUDENT ALTER COLUMN NAME VARCHAR(25);

DELETE STUDENT WHERE BRANCH ='ETC';



Exec sp_rename 'STUDENT', 'StudentInformation'

DELETE FROM STUDENT
DROP TABLE STUDENT;

SELECT * FROM StudentInformation
Exec sp_rename 'StudentInformation','STUDENT'
SELECT * FROM STUDENT

