USE BankAccountDatabase;

CREATE TABLE BORROW(
LOANNO VARCHAR(5) NOT NULL PRIMARY KEY,
CNAME VARCHAR(20),
BNAME VARCHAR(20),
AMOUNT DECIMAL(8,2),
CreatedDate DATETIME,
CreatedBy VARCHAR(100),
ModifiedDate DATETIME,
ModifiedBy VARCHAR(100)
)

SELECT * FROM BORROW;

DROP TABLE BORROW;

INSERT INTO BORROW (LOANNO,CNAME,BNAME,AMOUNT,CreatedBy,CreatedDate,ModifiedDate,ModifiedBy) VALUES
(201,'ANIL','VRCE',1000.00,'DINESH',GETDATE(),NULL,NULL),
(206,'RAHUL','KAROLBAGH',5000.00,'DINESH',GETDATE(),NULL,NULL),
(311,'SUNIL','MGROAD',3000.00,'DINESH',GETDATE(),NULL,NULL),
(321,'MADURI','CHANDINI',2000.00,'DINESH',GETDATE(),NULL,NULL),
(375,'PRAMOD','MGROAD',8000.00,'DINESH',GETDATE(),NULL,NULL);

SELECT * FROM BORROW WHERE CNAME LIKE '_C%';
SELECT * FROM BORROW WHERE AMOUNT BETWEEN 2000.00 AND 3000.00;

SELECT
CNAME,
AMOUNT, 
CAST((AMOUNT*10)/100 AS DECIMAL(8,2)) AS TA,
CAST((AMOUNT*20)/100 AS DECIMAL(8,2))AS DA, 
AMOUNT+((AMOUNT*10)/100+(AMOUNT*20)/100) AS TOTAL 
FROM BORROW;

SELECT * FROM BORROW WHERE AMOUNT NOT BETWEEN 2000 AND 8000

