USE BankAccountDatabase

CREATE TABLE BRANCH(
BNAME VARCHAR(20),
CITY VARCHAR(20)
);

SELECT * FROM BRANCH;

INSERT INTO BRANCH (BNAME,CITY) VALUES ('VRCE','NAGPUR'),('KAROLBAGH','DELHI'),('CHANDNI','DELHI'),('MGROAD','BANGALORE');

ALTER TABLE BRANCH ADD CreatedDate DATETIME,CreatedBy VARCHAR(30),ModifiedDate DATETIME,ModifiedBy VARCHAR(30);

UPDATE BRANCH SET CreatedDate=GETDATE(),CreatedBy='DINESH',ModifiedDate=NULL,ModifiedBy=NULL