USE BankAccountDatabase;

CREATE TABLE DEPOSIT (
ACTNO VARCHAR(5) NOT NULL PRIMARY KEY,
CNAME VARCHAR(20),
BNAME VARCHAR(30),
AMOUNT DECIMAL(8,2),
ADATE DATE
)
DROP TABLE DEPOSIT;

SELECT * FROM DEPOSIT;

INSERT INTO DEPOSIT (ACTNO,CNAME,BNAME,AMOUNT,ADATE) VALUES
(100,'ANIL','VRCE',1000.00,'01-MAR-95'),
(101,'SUNIL','MGROAD',5000.00,'04-JAN-96'),
(102,'RAHUL','KAROLBAGH',3500.00,'17-NOV-95'),
(103,'MADHURI','CHANDINI',1200.00,'17-DEC-95'),
(104,'PRAMOD','MGROAD',3000.00,'27-MAR-96'),
(105,'SANDIP','KAROLBAGH',2000.00,'31-MAR-96');

SELECT ACTNO, CNAME, BNAME, AMOUNT, FORMAT(ADATE, 'dd-MMM-yy') AS ADATE //5
FROM DEPOSIT;

SELECT CNAME,ACTNO FROM DEPOSIT;//6
SELECT CNAME FROM DEPOSIT WHERE ADATE >='17-NOV-95';

SELECT ACTNO,AMOUNT,CNAME FROM DEPOSIT WHERE ADATE BETWEEN '01-12-95' AND '01-06-96';
SELECT * FROM DEPOSIT WHERE CNAME LIKE 'C%'
SELECT * FROM DEPOSIT WHERE BNAME='CHANDNI' OR BNAME='MGROAD';
SELECT * FROM DEPOSIT WHERE NOT BNAME='CHANDNI' OR BNAME='MGROAD';

SELECT * FROM DEPOSIT WHERE AMOUNT>1000 ORDER BY CNAME ASC;

SELECT * FROM DEPOSIT WHERE AMOUNT>1000 ORDER BY CNAME DESC;

SELECT * FROM DEPOSIT WHERE CNAME LIKE '__A%' OR  CNAME LIKE '__D%'

SELECT DISTINCT BNAME FROM DEPOSIT;


ALTER TABLE DEPOSIT ADD SI FLOAT;

ALTER TABLE DEPOSIT DROP COLUMN SI;

UPDATE DEPOSIT SET AMOUNT=AMOUNT+(AMOUNT*0.1) WHERE BNAME='VRCE';

UPDATE DEPOSIT SET SI=AMOUNT-AMOUNT 

UPDATE DEPOSIT SET SI=NULL;

SELECT * FROM DEPOSIT;

UPDATE DEPOSIT SET SI=(AMOUNT*0.1) WHERE BNAME='VRCE';


