USE BankAccountDatabase

CREATE TABLE BRANCH(
BNAME VARCHAR(20),
CITY VARCHAR(20)
);

SELECT * FROM BRANCH;

INSERT INTO BRANCH (BNAME,CITY) VALUES ('VRCE','NAGPUR'),('KAROLBAGH','DELHI'),('CHANDNI','DELHI'),('MGROAD','BANGALORE');